# This is a template for the homebrew formula that will be created in exec/homebrew-rune
# The actual formula will be auto-generated by GitHub Actions

class Rune < Formula
  desc "A modern CLI text editor that bridges the gap between nano's simplicity and advanced features"
  homepage "https://github.com/exec/rune"
  version "0.1.0"
  
  if OS.mac?
    if Hardware::CPU.arm?
      url "https://github.com/exec/rune/releases/download/v#{version}/rune-darwin-aarch64.tar.gz"
      sha256 "PLACEHOLDER_AARCH64_SHA"
    else
      url "https://github.com/exec/rune/releases/download/v#{version}/rune-darwin-x86_64.tar.gz"
      sha256 "PLACEHOLDER_X86_64_SHA"
    end
  elsif OS.linux?
    if Hardware::CPU.arm?
      url "https://github.com/exec/rune/releases/download/v#{version}/rune-linux-aarch64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_AARCH64_SHA"
    else
      url "https://github.com/exec/rune/releases/download/v#{version}/rune-linux-x86_64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_X86_64_SHA"
    end
  end

  def install
    bin.install "rune"
  end

  test do
    # Test that the binary runs and shows help
    output = shell_output("#{bin}/rune --help")
    assert_match "A modern CLI text editor", output
  end
end